export const CELL_CLICKED = 'CELL_CLICKED';
export const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';
export const SET_MAX_LEVEL = 'SET_MAX_LEVEL';
export const SET_MIN_LEVEL = 'SET_START_LEVEL';
export const SET_REMAINING_FIELDS = 'SET_REMAINING_FIELDS';
export const SET_ACTIVE_FIELDS = 'SET_ACTIVE_FIELDS';
export const SET_VISITED_FIELDS = 'SET_VISITED_FIELDS';
export const SET_LIVES = 'SET_LIVES';
export const RESET_GAME = 'RESET_GAME';
export const SET_LEVELS_COMPLETED = 'SET_LEVELS_COMPLETED';

